version: "2.2"
services:
  database:
    image: "mariadb:10.3.23"
    ports:
        - "3306:3306"
    environment:
      MYSQL_DATABASE: blogs
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
        - ./db/data:/var/lib/mysql
        - ./db/dump:/tmp/dump:delegated
    networks:
      - blogs-net

networks:
  blogs-net:
    driver: bridge
